resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource

resources:
  - name: buildpacks-ci-orange-specific-target
    type: git
    source:
      private_key: {{buildpacks-ci-target-private-key}}
      uri: {{buildpacks-ci-target-git-uri}}
      branch: orange-specific

<% %w(master develop binary-built-output binary-builds new-buildpack-cve-notifications new-cve-notifications new-release-notifications).each do |branch_name| %>
  - name: buildpacks-ci-<%= branch_name %>-cf
    type: git
    source:
      branch: <%= branch_name %>
      uri: {{buildpacks-ci-git-https-uri}}

  - name: buildpacks-ci-<%= branch_name %>-target
    type: git
    source:
      private_key: {{buildpacks-ci-target-private-key}}
      uri: {{buildpacks-ci-target-git-uri}}
      branch: <%= branch_name %>
<% end %>


#### Machete ####
  - name: machete-cf
    type: git
    source:
      private_key: {{machete-target-private-key}}
      uri: {{machete-git-uri}}
      branch: master

  - name: machete-target
    type: git
    source:
      private_key: {{machete-target-private-key}}
      uri: {{machete-target-git-uri}}
      branch: master

#### Binary-Builder ####
  - name: binary-builder-cf
    type: git
    source:
      private_key: {{binary-builder-target-private-key}}
      uri: {{binary-builder-git-uri}}
      branch: master

  - name: binary-builder-target
    type: git
    source:
      private_key: {{binary-builder-target-private-key}}
      uri: {{binary-builder-target-git-uri}}
      branch: master

#### Others ####
  - name: deployments
    type: git
    source:
      private_key: {{buildpacks-ci-target-private-key}}
      uri: {{buildpacks-ci-target-git-uri}}
      branch: {{buildpacks-ci-target-branch}}

  - name: tools
    type: git
    source:
      uri: {{tools-git-uri}}

  - name: failure-alert
    type: slack-notification
    source:
      url: {{slack-webhook}}

#groups:
#- name: sync
#  jobs:
#  - sync-master-buildpack-ci
#  - sync-binary-builds-buildpack-ci
#  - sync-master-machete
#- name: all
#- name: auto-init
#  jobs:
#  - load-cfwebui

jobs:

<% %w(binary-builds new-buildpack-cve-notifications new-cve-notifications new-release-notifications).each do |branch_name| %>
- name: sync-buildpack-ci-<%= branch_name %>-merge
  plan:
  - aggregate:
    - get: buildpacks-ci-<%= branch_name %>-cf
      trigger: true
      attempts: 3
    - get: buildpacks-ci-<%= branch_name %>-target
      trigger: false
      attempts: 3
    - get: tools
      trigger: false
      attempts: 3
  - task: sync-fork
    input_mapping: {upstream: buildpacks-ci-<%= branch_name %>-cf, target: buildpacks-ci-<%= branch_name %>-target}
    file: tools/tasks/sync-branch-merge-no-tags.yml
    params:
      GH_USER: {{github-username}}
      GH_USER_EMAIL: {{github-email}}
      UPSTREAM_BRANCH: <%= branch_name %>
    on_failure:
      put: failure-alert
      params:
        channel: {{slack-channel}}
        text: Failed to synchronize $BUILD_JOB_NAME [[$BUILD_PIPELINE_NAME]($ATC_EXTERNAL_URL/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME)].
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        username: Concourse
    attempts: 4
  - put: buildpacks-ci-<%= branch_name %>-target
    params:
      repository: target-sync
    on_failure:
      put: failure-alert
      params:
        channel: {{slack-channel}}
        text: Failed cannot push $BUILD_JOB_NAME [[$BUILD_PIPELINE_NAME]($ATC_EXTERNAL_URL/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME)].
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        username: Concourse
<% end %>

<% %w(master develop binary-built-output).each do |branch_name| %>
- name: sync-buildpack-ci-<%= branch_name %>-rebase
  plan:
  - aggregate:
    - get: buildpacks-ci-<%= branch_name %>-cf
      trigger: true
      attempts: 3
    - get: buildpacks-ci-<%= branch_name %>-target
      trigger: false
      attempts: 3
    - get: tools
      trigger: false
      attempts: 3
  - task: sync-fork
    input_mapping: {upstream: buildpacks-ci-<%= branch_name %>-cf, target: buildpacks-ci-<%= branch_name %>-target}
    file: tools/tasks/sync-branch-rebase.yml
    params:
      GH_USER: {{github-username}}
      GH_USER_EMAIL: {{github-email}}
      UPSTREAM_BRANCH: <%= branch_name %>
    on_failure:
      put: failure-alert
      params:
        channel: {{slack-channel}}
        text: Failed to synchronize $BUILD_JOB_NAME [[$BUILD_PIPELINE_NAME]($ATC_EXTERNAL_URL/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME)].
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        username: Concourse
    attempts: 4
  - put: buildpacks-ci-<%= branch_name %>-target
    params:
      repository: target-sync
    on_failure:
      put: failure-alert
      params:
        channel: {{slack-channel}}
        text: Failed cannot push $BUILD_JOB_NAME [[$BUILD_PIPELINE_NAME]($ATC_EXTERNAL_URL/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME)].
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        username: Concourse
<% end %>


- name: sync-buildpack-ci-orange-specific
  plan:
  - aggregate:
    - get: buildpacks-ci-master-cf
      trigger: true
      attempts: 3
    - get: buildpacks-ci-orange-specific-target
      trigger: false
      attempts: 3
    - get: tools
      trigger: false
      attempts: 3
  - task: sync-fork
    input_mapping: {upstream: buildpacks-ci-master-cf, target: buildpacks-ci-orange-specific-target}
    file: tools/tasks/sync-branch-rebase.yml
    params:
      GH_USER: {{github-username}}
      GH_USER_EMAIL: {{github-email}}
      UPSTREAM_BRANCH: master
    on_failure:
      put: failure-alert
      params:
        channel: {{slack-channel}}
        text: Failed to synchronize $BUILD_JOB_NAME [[$BUILD_PIPELINE_NAME]($ATC_EXTERNAL_URL/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME)].
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        username: Concourse
    attempts: 3
  - put: buildpacks-ci-orange-specific-target
    params:
      repository: target-sync
      rebase: false
    on_failure:
      put: failure-alert
      params:
        channel: {{slack-channel}}
        text: Failed cannot push $BUILD_JOB_NAME [[$BUILD_PIPELINE_NAME]($ATC_EXTERNAL_URL/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME)].
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        username: Concourse

- name: sync-master-machete
  plan:
  - aggregate:
    - get: machete-cf
      trigger: true
      attempts: 3
    - get: machete-target
      trigger: false
      attempts: 3
    - get: tools
      trigger: false
      attempts: 3
  - task: sync-fork
    input_mapping: {upstream: machete-cf, target: machete-target}
    file: tools/tasks/sync-branch-merge-no-tags.yml
    params:
       GH_USER: {{github-username}}
       GH_USER_EMAIL: {{github-email}}
       UPSTREAM_BRANCH: master
    on_failure:
      put: failure-alert
      params:
        channel: {{slack-channel}}
        text: Failed to synchronize machete master [[$BUILD_PIPELINE_NAME]($ATC_EXTERNAL_URL/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME)].
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        username: Concourse
    attempts: 3
  - put: machete-target
    params:
      repository: target-sync
    on_failure:
      put: failure-alert
      params:
        channel: {{slack-channel}}
        text: Failed cannot push machete master [[$BUILD_PIPELINE_NAME]($ATC_EXTERNAL_URL/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME)].
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        username: Concourse

- name: sync-master-binary-builder
  plan:
  - aggregate:
    - get: binary-builder-cf
      trigger: true
      attempts: 3
    - get: binary-builder-target
      trigger: false
      attempts: 3
    - get: tools
      trigger: false
      attempts: 3
  - task: sync-fork
    input_mapping: {upstream: binary-builder-cf, target: binary-builder-target}
    file: tools/tasks/sync-branch-rebase.yml
    params:
      GH_USER: {{github-username}}
      GH_USER_EMAIL: {{github-email}}
      UPSTREAM_BRANCH: master
    on_failure:
      put: failure-alert
      params:
        channel: {{slack-channel}}
        text: Failed to synchronize binary-builder master [[$BUILD_PIPELINE_NAME]($ATC_EXTERNAL_URL/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME)].
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        username: Concourse
    attempts: 3
  - put: binary-builder-target
    params:
      repository: target-sync
    on_failure:
      put: failure-alert
      params:
        channel: {{slack-channel}}
        text: Failed cannot push binary-builder master [[$BUILD_PIPELINE_NAME]($ATC_EXTERNAL_URL/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME)].
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        username: Concourse

