resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource

resources:
  - name: buildpacks-ci-cf
    type: git
    source:
      branch: master
      uri: {{buildpacks-ci-git-https-uri}}

  - name: buildpacks-ci-target
    type: git
    source:
      private_key: {{buildpacks-ci-target-private-key}}
      uri: {{buildpacks-ci-target-git-uri}}
      branch: master

  - name: buildpacks-ci-binary-builds-cf
    type: git
    source:
      branch: binary-builds
      uri: {{buildpacks-ci-git-https-uri}}

  - name: buildpacks-ci-binary-builds-target
    type: git
    source:
      private_key: {{buildpacks-ci-target-private-key}}
      uri: {{buildpacks-ci-target-git-uri}}
      branch: binary-builds

  - name: buildpacks-ci-binary-built-output-cf
    type: git
    source:
      branch: binary-built-output
      uri: {{buildpacks-ci-git-https-uri}}

  - name: buildpacks-ci-binary-built-output-target
    type: git
    source:
      private_key: {{buildpacks-ci-target-private-key}}
      uri: {{buildpacks-ci-target-git-uri}}
      branch: binary-built-output

  - name: buildpacks-ci-develop-cf
    type: git
    source:
      branch: develop
      uri: {{buildpacks-ci-git-https-uri}}

  - name: buildpacks-ci-develop-target
    type: git
    source:
      private_key: {{buildpacks-ci-target-private-key}}
      uri: {{buildpacks-ci-target-git-uri}}
      branch: develop

  - name: buildpacks-ci-orange-specific-target
    type: git
    source:
      private_key: {{buildpacks-ci-target-private-key}}
      uri: {{buildpacks-ci-target-git-uri}}
      branch: orange-specific

#### Machete ####
  - name: machete-cf
    type: git
    source:
      private_key: {{machete-target-private-key}}
      uri: {{machete-git-uri}}
      branch: master

  - name: machete-target
    type: git
    source:
      private_key: {{machete-target-private-key}}
      uri: {{machete-target-git-uri}}
      branch: master

#### Binary-Builder ####
  - name: binary-builder-cf
    type: git
    source:
      private_key: {{binary-builder-target-private-key}}
      uri: {{binary-builder-git-uri}}
      branch: master

  - name: binary-builder-target
    type: git
    source:
      private_key: {{binary-builder-target-private-key}}
      uri: {{binary-builder-target-git-uri}}
      branch: master


#### Php-Buildpack ####
  - name: php-buildpack-cf
    type: git
    source:
      private_key: {{php-buildpack-target-private-key}}
      uri: {{php-buildpack-git-uri}}
      branch: master

  - name: php-buildpack-target
    type: git
    source:
      private_key: {{php-buildpack-target-private-key}}
      uri: {{php-buildpack-target-git-uri}}
      branch: master

  - name: php-buildpack-develop-cf
    type: git
    source:
      private_key: {{php-buildpack-target-private-key}}
      uri: {{php-buildpack-git-uri}}
      branch: develop

  - name: php-buildpack-develop-target
    type: git
    source:
      private_key: {{php-buildpack-target-private-key}}
      uri: {{php-buildpack-target-git-uri}}
      branch: develop

#### Others ####
  - name: deployments
    type: git
    source:
      private_key: {{buildpacks-ci-target-private-key}}
      uri: {{buildpacks-ci-target-git-uri}}
      branch: {{buildpacks-ci-target-branch}}

  - name: tools
    type: git
    source:
      uri: {{tools-git-uri}}

  - name: slack-alert
    type: slack-notification
    source:
      url: {{slack-webhook}}

#groups:
#- name: sync
#  jobs:
#  - sync-master-buildpack-ci
#  - sync-binary-builds-buildpack-ci
#  - sync-master-machete
#- name: all
#- name: auto-init
#  jobs:
#  - load-cfwebui

jobs:
- name: sync-buildpack-ci-master
  plan:
  - aggregate:
    - get: buildpacks-ci-cf
      trigger: true
      attempts: 3
    - get: buildpacks-ci-target
      trigger: false
      attempts: 3
    - get: tools
      trigger: false
      attempts: 3
  - task: sync-fork
    input_mapping: {upstream: buildpacks-ci-cf, target: buildpacks-ci-target}
    file: tools/tasks/sync-branch-rebase.yml
    params:
      GH_USER: {{github-username}}
      GH_USER_EMAIL: {{github-email}}
      UPSTREAM_BRANCH: master
    on_failure:
      put: slack-alert
      params:
        channel: {{slack-channel}}
        text: Failed to synchronize master [[$BUILD_PIPELINE_NAME]($ATC_EXTERNAL_URL/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME)].
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        username: Concourse
    attempts: 3
  - put: buildpacks-ci-target
    params:
      repository: target-sync
    on_failure:
      put: slack-alert
      params:
        channel: {{slack-channel}}
        text: Failed cannot push master [[$BUILD_PIPELINE_NAME]($ATC_EXTERNAL_URL/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME)].
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        username: Concourse
  - put: slack-alert
    params:
      channel: {{slack-channel}}
      text: Sucessfully synchronized master [[$BUILD_PIPELINE_NAME]($ATC_EXTERNAL_URL/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME)].
      icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
      username: Concourse


- name: sync-buildpack-ci-binary-builds
  plan:
  - aggregate:
    - get: buildpacks-ci-binary-builds-cf
      trigger: true
      attempts: 3
    - get: buildpacks-ci-binary-builds-target
      trigger: false
      attempts: 3
    - get: tools
      trigger: false
      attempts: 3
  - task: sync-fork
    input_mapping: {upstream: buildpacks-ci-binary-builds-cf, target: buildpacks-ci-binary-builds-target}
    file: tools/tasks/sync-branch-rebase.yml
    params:
      GH_USER: {{github-username}}
      GH_USER_EMAIL: {{github-email}}
      UPSTREAM_BRANCH: binary-builds
    on_failure:
      put: slack-alert
      params:
        channel: {{slack-channel}}
        text: Failed to synchronize binary-builds [[$BUILD_PIPELINE_NAME]($ATC_EXTERNAL_URL/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME)].
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        username: Concourse
    attempts: 4
  - put: buildpacks-ci-binary-builds-target
    params:
      repository: target-sync
    on_failure:
      put: slack-alert
      params:
        channel: {{slack-channel}}
        text: Failed cannot push binary-builds [[$BUILD_PIPELINE_NAME]($ATC_EXTERNAL_URL/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME)].
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        username: Concourse
  - put: slack-alert
    params:
      channel: {{slack-channel}}
      text: Sucessfully synchronized binary-builds [[$BUILD_PIPELINE_NAME]($ATC_EXTERNAL_URL/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME)].
      icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
      username: Concourse


- name: sync-buildpack-ci-develop
  plan:
  - aggregate:
    - get: buildpacks-ci-develop-cf
      trigger: true
      attempts: 3
    - get: buildpacks-ci-develop-target
      trigger: false
      attempts: 3
    - get: tools
      trigger: false
      attempts: 3
  - task: sync-fork
    input_mapping: {upstream: buildpacks-ci-develop-cf, target: buildpacks-ci-develop-target}
    file: tools/tasks/sync-branch-rebase.yml
    params:
      GH_USER: {{github-username}}
      GH_USER_EMAIL: {{github-email}}
      UPSTREAM_BRANCH: develop
    on_failure:
      put: slack-alert
      params:
        channel: {{slack-channel}}
        text: Failed to synchronize master [[$BUILD_PIPELINE_NAME]($ATC_EXTERNAL_URL/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME)].
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        username: Concourse
    attempts: 3
  - put: buildpacks-ci-develop-target
    params:
      repository: target-sync
    on_failure:
      put: slack-alert
      params:
        channel: {{slack-channel}}
        text: Failed cannot push master [[$BUILD_PIPELINE_NAME]($ATC_EXTERNAL_URL/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME)].
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        username: Concourse
  - put: slack-alert
    params:
      channel: {{slack-channel}}
      text: Sucessfully synchronized master [[$BUILD_PIPELINE_NAME]($ATC_EXTERNAL_URL/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME)].
      icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
      username: Concourse

- name: sync-buildpack-ci-orange-specific
  plan:
  - aggregate:
    - get: buildpacks-ci-target
      trigger: true
      attempts: 3
    - get: buildpacks-ci-orange-specific-target
      trigger: false
      attempts: 3
    - get: tools
      trigger: false
      attempts: 3
  - task: sync-fork
    input_mapping: {upstream: buildpacks-ci-target, target: buildpacks-ci-orange-specific-target}
    file: tools/tasks/sync-branch-rebase.yml
    params:
      GH_USER: {{github-username}}
      GH_USER_EMAIL: {{github-email}}
      UPSTREAM_BRANCH: orange-specific
    on_failure:
      put: slack-alert
      params:
        channel: {{slack-channel}}
        text: Failed to synchronize orange-specific [[$BUILD_PIPELINE_NAME]($ATC_EXTERNAL_URL/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME)].
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        username: Concourse
    attempts: 3
  - put: buildpacks-ci-orange-specific-target
    params:
      repository: target-sync
    on_failure:
      put: slack-alert
      params:
        channel: {{slack-channel}}
        text: Failed cannot push orange-specific [[$BUILD_PIPELINE_NAME]($ATC_EXTERNAL_URL/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME)].
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        username: Concourse
  - put: slack-alert
    params:
      channel: {{slack-channel}}
      text: Sucessfully synchronized orange-specific [[$BUILD_PIPELINE_NAME]($ATC_EXTERNAL_URL/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME)].
      icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
      username: Concourse

- name: sync-buildpack-ci-binary-built-output
  plan:
  - aggregate:
    - get: buildpacks-ci-binary-built-output-cf
      trigger: true
      attempts: 3
    - get: buildpacks-ci-binary-built-output-target
      trigger: false
      attempts: 3
    - get: tools
      trigger: false
      attempts: 3
  - task: sync-fork
    input_mapping: {upstream: buildpacks-ci-binary-builds-cf, target: buildpacks-ci-binary-builds-target}
    file: tools/tasks/sync-branch-rebase.yml
    params:
      GH_USER: {{github-username}}
      GH_USER_EMAIL: {{github-email}}
      UPSTREAM_BRANCH: binary-built-output
    on_failure:
      put: slack-alert
      params:
        channel: {{slack-channel}}
        text: Failed to synchronize $BUILD_JOB_NAME [[$BUILD_PIPELINE_NAME]($ATC_EXTERNAL_URL/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME)].
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        username: Concourse
    attempts: 4
  - put: buildpacks-ci-binary-built-output-target
    params:
      repository: target-sync
    on_failure:
      put: slack-alert
      params:
        channel: {{slack-channel}}
        text: Failed cannot push $BUILD_JOB_NAME [[$BUILD_PIPELINE_NAME]($ATC_EXTERNAL_URL/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME)].
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        username: Concourse
  - put: slack-alert
    params:
      channel: {{slack-channel}}
      text: Sucessfully synchronized $BUILD_JOB_NAME [[$BUILD_PIPELINE_NAME]($ATC_EXTERNAL_URL/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME)].
      icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
      username: Concourse

- name: sync-master-machete
  plan:
  - aggregate:
    - get: machete-cf
      trigger: true
      attempts: 3
    - get: machete-target
      trigger: false
      attempts: 3
    - get: tools
      trigger: false
      attempts: 3
  - task: sync-fork
    input_mapping: {upstream: machete-cf, target: machete-target}
    file: tools/tasks/sync-branch-merge.yml
    params:
       GH_USER: {{github-username}}
       GH_USER_EMAIL: {{github-email}}
       UPSTREAM_BRANCH: master
    on_failure:
      put: slack-alert
      params:
        channel: {{slack-channel}}
        text: Failed to synchronize machete master [[$BUILD_PIPELINE_NAME]($ATC_EXTERNAL_URL/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME)].
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        username: Concourse
    attempts: 3
  - put: machete-target
    params:
      repository: target-sync
    on_failure:
      put: slack-alert
      params:
        channel: {{slack-channel}}
        text: Failed cannot push machete master [[$BUILD_PIPELINE_NAME]($ATC_EXTERNAL_URL/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME)].
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        username: Concourse
  - put: slack-alert
    params:
      channel: {{slack-channel}}
      text: Sucessfully synchronized machete master [[$BUILD_PIPELINE_NAME]($ATC_EXTERNAL_URL/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME)].
      icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
      username: Concourse


- name: sync-master-binary-builder
  plan:
  - aggregate:
    - get: binary-builder-cf
      trigger: true
      attempts: 3
    - get: binary-builder-target
      trigger: false
      attempts: 3
    - get: tools
      trigger: false
      attempts: 3
  - task: sync-fork
    input_mapping: {upstream: binary-builder-cf, target: binary-builder-target}
    file: tools/tasks/sync-branch-rebase.yml
    params:
      GH_USER: {{github-username}}
      GH_USER_EMAIL: {{github-email}}
      UPSTREAM_BRANCH: master
    on_failure:
      put: slack-alert
      params:
        channel: {{slack-channel}}
        text: Failed to synchronize binary-builder master [[$BUILD_PIPELINE_NAME]($ATC_EXTERNAL_URL/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME)].
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        username: Concourse
    attempts: 3
  - put: binary-builder-target
    params:
      repository: target-sync
    on_failure:
      put: slack-alert
      params:
        channel: {{slack-channel}}
        text: Failed cannot push binary-builder master [[$BUILD_PIPELINE_NAME]($ATC_EXTERNAL_URL/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME)].
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        username: Concourse
  - put: slack-alert
    params:
      channel: {{slack-channel}}
      text: Sucessfully synchronized binary-builder master [[$BUILD_PIPELINE_NAME]($ATC_EXTERNAL_URL/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME)].
      icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
      username: Concourse