resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource

resources:

#### Php-Buildpack ####
#  - name: php-buildpack-develop-cf
#    type: git
#    source:
#      private_key: {{php-buildpack-target-private-key}}
#      uri: {{php-buildpack-git-uri}}
#      branch: develop
#
#  - name: php-buildpack-develop-target
#    type: git
#    source:
#      private_key: {{php-buildpack-target-private-key}}
#      uri: {{php-buildpack-target-git-uri}}
#      branch: develop

<% %w(master develop).each do |branch_name| %>
<% %w(nodejs staticfile ruby go php).each do |language| %>
  - name: <%= language %>-buildpack-<%= branch_name %>-cf
    type: git
    source:
#      private_key: {{<%= language %>-buildpack-target-private-key}}
      uri: {{<%= language %>-buildpack-git-uri}}
      branch: <%= branch_name %>

  - name: <%= language %>-buildpack-<%= branch_name %>-target
    type: git
    source:
      private_key: {{<%= language %>-buildpack-target-private-key}}
      uri: {{<%= language %>-buildpack-target-git-uri}}
      branch: <%= branch_name %>

<% end %>
<% end %>

#### Others ####
  - name: deployments
    type: git
    source:
      private_key: {{buildpacks-ci-target-private-key}}
      uri: {{buildpacks-ci-target-git-uri}}
      branch: {{buildpacks-ci-target-branch}}

  - name: tools
    type: git
    source:
      uri: {{tools-git-uri}}

  - name: slack-alert
    type: slack-notification
    source:
      url: {{slack-webhook}}


jobs:

<% %w(master develop).each do |branch_name| %>
<% %w(ruby staticfile go php).each do |language| %>
- name: sync-<%= branch_name %>-<%= language %>-buildpack
  plan:
  - aggregate:
    - get: <%= language %>-buildpack-<%= branch_name %>-cf
      trigger: true
      attempts: 3
    - get: <%= language %>-buildpack-<%= branch_name %>-target
      trigger: false
      attempts: 3
    - get: tools
      trigger: false
      attempts: 3
  - task: sync-fork
    input_mapping: {upstream: <%= language %>-buildpack-<%= branch_name %>-cf, target: <%= language %>-buildpack-<%= branch_name %>-target}
    file: tools/tasks/sync-branch-merge.yml
    params:
      GH_USER: {{github-username}}
      GH_USER_EMAIL: {{github-email}}
      UPSTREAM_BRANCH: <%= branch_name %>
    on_failure:
      put: slack-alert
      params:
        channel: {{slack-channel}}
        text: Failed to synchronize $BUILD_JOB_NAME [[$BUILD_PIPELINE_NAME]($ATC_EXTERNAL_URL/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME)].
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        username: Concourse
    attempts: 4
  - put: <%= language %>-buildpack-<%= branch_name %>-target
    params:
      repository: target-sync
    on_failure:
      put: slack-alert
      params:
        channel: {{slack-channel}}
        text: Failed cannot push $BUILD_JOB_NAME [[$BUILD_PIPELINE_NAME]($ATC_EXTERNAL_URL/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME)].
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        username: Concourse
  - put: slack-alert
    params:
      channel: {{slack-channel}}
      text: Sucessfully synchronized $BUILD_JOB_NAME [[$BUILD_PIPELINE_NAME]($ATC_EXTERNAL_URL/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME)].
      icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
      username: Concourse
<% end %>
<% end %>


#- name: sync-develop-php-buildpack
#  plan:
#  - aggregate:
#    - get: php-buildpack-develop-cf
#      trigger: true
#      attempts: 3
#    - get: php-buildpack-develop-target
#      trigger: false
#      attempts: 3
#    - get: tools
#      trigger: false
#      attempts: 3
#  - task: sync-fork
#    input_mapping: {upstream: php-buildpack-develop-cf, target: php-buildpack-develop-target}
#    file: tools/tasks/sync-branch-rebase.yml
#    params:
#      GH_USER: {{github-username}}
#      GH_USER_EMAIL: {{github-email}}
#      UPSTREAM_BRANCH: develop
#    on_failure:
#      put: slack-alert
#      params:
#        channel: {{slack-channel}}
#        text: Failed to synchronize $BUILD_JOB_NAME [[$BUILD_PIPELINE_NAME]($ATC_EXTERNAL_URL/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME)].
#        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
#        username: Concourse
#    attempts: 3
#  - put: php-buildpack-develop-target
#    params:
#      repository: target-sync
#    on_failure:
#      put: slack-alert
#      params:
#        channel: {{slack-channel}}
#        text: Failed cannot push $BUILD_JOB_NAME [[$BUILD_PIPELINE_NAME]($ATC_EXTERNAL_URL/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME)].
#        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
#        username: Concourse
#  - put: slack-alert
#    params:
#      channel: {{slack-channel}}
#      text: Sucessfully synchronized $BUILD_JOB_NAME [[$BUILD_PIPELINE_NAME]($ATC_EXTERNAL_URL/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME)].
#      icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
#      username: Concourse